function on_xml_read()
	RegisterScriptCallback("on_xml_read", function(xml_file_name, xml_obj)
		if xml_file_name == [[ui\textures_descr\ui_item.xml]] then
			local new_node = 
			[[
            <file name="ui\ui_batch_maintain">
                <texture id="ui_batch_maintenance" x="0" y="0" width="1920" height="1080"/>
            </file>
			]]

			xml_obj:insertFromXMLString(new_node)
		end
    end)
end